name: 🎉 Release Binary
on:
  create:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      
      - name: "Set up Go"
        uses: actions/setup-go@v2
        with: 
          go-version: 1.18

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}
      
      - name: "Create release on GitHub"
        uses: goreleaser/goreleaser-action@v2
        with:
          args: "release --rm-dist"
          version: latest
          workdir: v2/
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"